<form class="mb-5">
    <div class="mb-3">
        <label class="form-label">...</label>
        <input class="form-control">
    </div>
    ...
        ...
        <select class="form-select">
            <option>...</option>
            ...
        </select>
    ...
    <button type="submit" class="btn btn-primary">Enviar</button>